name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: python hello.py
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v4
     - uses: action/upload-artifact@v4
       with:
        name: hello
        path: .
    
